baseURL: "https://yabogv.github.io" 
title: Yabo Gwladys Vidogbena
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        # - name: Data
        #   url: data/
        #   weight: 3 
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 3

params:
    description: "Yabo Gwladys Vidogbena--Ph.D candidate in Economics at the University of Houston. My main interest is in development Economics, specifically in education. My primary research agenda aims at understanding the low level of learning (learning crisis) in Sub-Saharan African countries. I am on the job market 2024-2025 and you can find my [CV here]."
    author: Yabo Gwladys Vidogbena
    # keywords: "Yabo Gwladys Vidogbena, PhD Candidate, Economics, University of Houston, Development Economics"
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yabo Gwladys Vidogbena
          subtitle: "Hi and Welcome! I am a Postdoctoral Fellow at the Population Studies Center (PSC) and an instructor in the Department of economics at the University of Pennsylvania. I obtained my Ph.D. in economics from the University of Houston. You can find my CV <a href='cv_yabo_vidogbena_noTA_jan_26.pdf' style='color:#009e73; font-weight:bold;'> here</a>."
          imageUrl: "Yabo2040_squared_high_res.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Yabo Gwladys Vidogbena
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            # - name: Data
            #   url: data/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:yvidogbena@uh.edu
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: LinkedIn
          url: https://www.linkedin.com/in/yabo-gwladys-vidogbena-b2b544104/
        - name: GitHub
          url: https://github.com/yaboGV
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Twitter
        #   url: https://x.com/Ladys_gw

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yabo Gwladys Vidogbena"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2